trabajo_fase_2/trabajo_fase_2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/',include('web.urls')),
]

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

trabajo_fase_2/web/urls.py
from django.urls import path
from . import views
urlpatterns = [
    
    path('',views.index,name='index'),
    path('novedades/',views.novedades,name='novedades'),
    path('dulces/',views.dulces,name='dulces'),
    path('saladas/',views.saladas,name='saladas'),
    path('pret/',views.pret,name='pret'),
    path('pie/',views.pie,name='pie'),
    path('capu/',views.capu,name='capu'),
    path('bebidas/',views.bebidas,name='bebidas'),
    path('autor/<int:pk>', views.AutorDetailView.as_view(), name='autor-detail'),
]

urlpatterns += [
    path('autor/create/',views.AutorCreate.as_view(), name='autor_create'),
    path('autor/<int:pk>/update/',views.AutorUpdate.as_view(), name='autor_update'),
    path('autor/<int:pk>/delete/',views.AutorDelete.as_view(), name='autor_delete'),

]

trabajo_fase_2/web/models.py
from django.db import models
from django.urls import reverse
import uuid


class Preparacion(models.Model):
    #Model representing a book genre."""
	tipo_prep = models.CharField(max_length=200)
	
	def __str__(self):
		return self.tipo_prep



class Receta(models.Model):

	titulo = models.CharField(max_length=100)
	receta = models.TextField(max_length=3000)
	autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True)
	preparacion = models.ManyToManyField(Preparacion)

	def __str__(self):
		return self.titulo

	def get_absolute_url(self):
		return reverse('receta-detail', args=[str(self.id)])	
		

class Autor(models.Model):
	
	pnombre = models.CharField(max_length=100)
	papellido = models.CharField(max_length=100)
	fechanac = models.DateField(null=True, blank=True)
	fechamuerte = models.DateField('Muerto', null=True, blank=True)

	class Meta:
		ordering = ['papellido', 'pnombre']


	def get_absolute_url(self):
		return reverse('autor-detail', args=[str(self.id)])

	def __str__(self):
		return f'{self.papellido}, {self.pnombre}'		

trabajo_fase_2/web/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from . models import Preparacion, Receta, Autor

# Create your views here.
def index(request):

    num_recetas=Receta.objects.all().count()
    num_autores=Autor.objects.count()

    return render(
        request,
        'index.html',
        context={'num_recetas':num_recetas, 'num_autores':num_autores},
    )

def novedades(request):
    return render(
        request, 
        'novedades.html',
)

def dulces(request):
    return render(
        request, 
        'dulces.html',
)

def saladas(request):
    return render(
        request, 
        'saladas.html',
)

def bebidas(request):
    return render(
        request, 
        'bebidas.html',
)

def pret(request):
    return render(
        request, 
        'pret.html',
)

def pie(request):
    return render(
        request, 
        'pie.html',
)

def capu(request):
    return render(
        request, 
        'capu.html',
)

class AutorCreate(CreateView):
    model = Autor
    fields = ['pnombre', 'papellido', 'fechanac', 'fechamuerte']

class AutorUpdate(UpdateView):
    model = Autor
    fields = ['pnombre', 'papellido', 'fechanac', 'fechamuerte']

class AutorDelete(DeleteView):
    model = Autor
    success_url = reverse_lazy('index')


from django.views import generic
class AutorDetailView(generic.DetailView):
    model = Autor

trabajo_fase_2/web/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>

   <title>Local Library</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <!-- Add additional CSS in static file -->
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">   

  </head>
  <body>

    <div>
      <nav class="navbar navbar-expand-md navbar-dark text-white bg-dark">
        <a class="navbar-brand" href="#">Toffee</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"  aria-controls="" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>      
        <div class="collapse navbar-collapse" id="">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Inicio</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="" id="dropdown01" data-toggle="dropdown" aria-haspopup="true">Categorias</a>
              <div class="dropdown-menu" aria-labelledby="dropdown01">
                <a class="dropdown-item" href="{% url 'novedades' %}">Novedades</a>
                <a class="dropdown-item" href="{% url 'dulces' %}">Recetas dulces</a>
                <a class="dropdown-item" href="{% url 'saladas' %}">Recetas saladas</a>
                <a class="dropdown-item" href="{% url 'bebidas' %}">Bebidas Frias/calientes </a>
              </div>
            </li>
          </ul>        
    </nav> 
    </div>  
    {% block content %} {% endblock %}
    <footer class="container">
      <p class="float-right"><a href="#">Ir al inicio</a></p>
      <p>&copy; 2019-2020 Bastian Pinto-Bernardo Valderrama-Diego Jorquera. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>   
  </body>
</html>

trabajo_fase_2/web/templates/bebidas.html
{% extends "base_generic.html" %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}">

    <title>Toffe</title>
    <link rel="icon" href="{% static 'img/icon.jpg' %}">
  </head>

  <body>
    {% block content %}


    <section  class="jumbotron bg-info">
      <div class="container ">
        <h1 class="h1"> <strong>Novedades de las Recetas</strong> </h1>
        <p class="h2"><strong>Desde los pasteles hasta las bebidas.</strong> </p>
      </div>
    </section>
    </header>
      
    
    <section class="main container">
        <nav aria-label="breadcrumb">
            <section class="col-md-9">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
                <li class="breadcrumb-item"><a href="{% url 'novedades' %}">Categoría</a></li>
                <li class="breadcrumb-item active">Bebidas frias/calientes</li>
              </ol>
          <article class="post clearfix">
            <a href="{% url 'capu' %}" class="thumb pull-left">
              <img src="{% static 'img/cap1.jpg' %}" alt="" style="float: left;" width="400" height="250"><h2 class="h2-2"><strong>Receta de capuchino, paso a paso</strong></h2>
            </a>
            <p><span class="psfecha">13 de Octubre del 2020</span> por <span class="posts autor"><a href="#">Bernardo Valderrama</a></span></p>
            <p class="pcontenido text-justify">
                Es una bebida nacida en Italia, preparada con café expreso y leche montada con vapor para otorgarle cremosidad. Hoy en día, el capuchino no solo es común en Italia sino también en todo el mundo. El capuchino se extendió inicialmente por toda Europa, adquiriendo su forma definitiva alrededor de 1950, para luego llegar a Sudamérica, 
                popularizándose en países como Argentina, Brasil, Bolivia, Chile, Paraguay, Perú y Uruguay.
            </p>
            <div class="botones">
              <a href="{% url 'capu' %}" class="btn btn-info">Leer Más</a>
            </div>
          </article>
        </section>
      </section>

    
    
   
   

  </body>
  
 
      
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock %}

trabajo_fase_2/web/templates/capu.html
{% extends "base_generic.html" %}
{% block content %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}">

    <title>Toffe</title>
    <link rel="icon" href="{% static 'img/icon.jpg' %}">
  </head>

  <body>
    <header>

    </header>
    <section  class="jumbotron bg-info">
      <div class="container ">
        <h1 class="h1"> <strong>Novedades de las Recetas</strong> </h1>
        <p class="h2"><strong>Desde los pasteles hasta las bebidas.</strong> </p>
      </div>
    </section>
    </header>
      
    
    <section class="main container">
      <nav aria-label="breadcrumb">
        <section class="col-md-9">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{% url 'novedades' %}">Categoría</a></li>
            <li class="breadcrumb-item"><a href="{% url 'bebidas' %}">Bebidas frias/calientes</a></li>
            <li class="breadcrumb-item active">Capuchino</li>
          </ol>
          <article class="post clearfix">
            <a href="#" class="thumb pull-left">
              <img src="{% static 'img/cap1.jpg' %}" alt="" style="float: left;" width="400" height="250"><h2 class="h2-2"> <strong> Receta de capuchino, paso a paso </strong></h2>
            </a>
            <p><span class="psfecha">13 de Octubre del 2020</span> por <span class="posts autor"><a href="#">Bernardo Valderrama</a></span></p>
            <p class="pcontenido text-justify">
                Es una bebida nacida en Italia, preparada con café expreso y leche montada con vapor para otorgarle cremosidad. Hoy en día, el capuchino no solo es común en Italia sino también en todo el mundo. El capuchino se extendió inicialmente por toda Europa, adquiriendo su forma definitiva alrededor de 1950, para luego llegar a Sudamérica, 
                popularizándose en países como Argentina, Brasil, Bolivia, Chile, Paraguay, Perú y Uruguay.
              <p>Ingredientes:
                <ul type="circle">
                  <li>Una taza de café preparado a gusto</li>
                  <li>Cacao en polvo para decoración</li>
                  <li>Una taza de leche entera</li>
                </ul>
              </p>
              <p>
                Preparación:
                <ol type="1">
                    <li>Para empezar ponemos la leche en un bote con tapa o en un recipiente hermético. 
                        Tapamos bien y agitamos con fuerza durante 30 seg a un minuto hasta que la leche espume bastante y 
                        aumente mucho su tamaño.</li><hr>
                    <li>Ese es el recurso rápido pero este proceso lo puedes hacer en una batidora durante 2 min y 
                        el resultado será aún más espumoso.</li><hr>
                    <li>Inmediatamente ponemos la leche ya batida en el microondas unos 30 seg y así la espuma se compacta.
                         Si has usado un hermético o un bote, úsalo para el microondas también.</li><hr>
                    <li>Ponemos primero esta espuma espesa de leche en la taza de servicio y vamos vertiendo el café azucarado por un lateral con cuidado. De esta forma el café se va abajo y la espuma queda arriba. 
                        Decoramos espolvoreando con el cacao en polvo y servimos al momento, muy caliente.</li>            
                </ol>
              </p>  
            </p>
          </article>
        </section>
      </nav>
    </section>
  </body>  
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock %}

trabajo_fase_2/web/templates/dulces.html
{% extends "base_generic.html" %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}">

    <title>Toffe</title>
    <link rel="icon" href="{% static 'img/icon.jpg' %}">
  </head>

  <body>
    {% block content %}
    <header>
      
    </header>
    <section  class="jumbotron bg-info">
      <div class="container ">
        <h1 class="h1"> <strong>Novedades de las Recetas</strong> </h1>
        <p class="h2"><strong>Desde los pasteles hasta las bebidas.</strong> </p>
      </div>
    </section>
    </header>
      
    
    <section class="main container">
      <nav aria-label="breadcrumb">
        <section class="col-md-9">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{% url 'novedades' %}">Categorias</a></li>
            <li class="breadcrumb-item active">Recetas dulces</li>
          </ol>
          <article class="post clearfix">
            <a href="{% url 'pie' %}" class="thumb pull-left">
              <img src="{% static 'img/pie1.jpg'     %}" alt="" style="float: left;" width="400" height="250"><h2 class="h2-2"> <strong> Receta pie de limon, paso a paso </strong></h2>
            </a>
            <p><span class="psfecha">14 de Octubre del 2020</span> por <span class="posts autor"><a href="#">Diego Jorquera</a></span></p>
            <p class="pcontenido text-justify">
              El pie de limón es una receta tradicional dentro de la cocina francesa, Estado Unidense y de Reino Unido, aunque es un postre conocido y consumido
              por todo el mundo. Consiste en una base de masa quebradiza u hojaldre, relleno de crema de limon, en ocaciones se cubre con una capa de merengue.
            </p>

            <div class="botones">
              <a href="{% url 'pie' %}" class="btn btn-info">Leer Más</a>
            </div>
          </article>
        </section>
      </nav>
    </section>

    
    
   
   

  </body>
  
 
      
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock %}

trabajo_fase_2/web/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        {% load static %}
        <div class="carousel-inner">
          <div class="carousel-item active" style="height: 100vh">
            <img src="{% static 'img/f1.jpg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h1 class="h1">Bienvenido a Toffe</h1>
              <p>Aqui podras encontar las mejores recetas de las cafeterias.</p>
            </div>
          </div>
          <div class="carousel-item" style="height: 100vh ">
            <img src="{% static 'img/f2.jpg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h1 class="h1">Bienvenido a Toffe</h1>
              <p>Aqui podras encontar las mejores recetas de las cafeterias.</p>
            </div>
          </div>
          <div class="carousel-item" style="height: 100vh">
            <img src="{% static 'img/f3.jpg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h1 class="h1">Bienvenido a Toffe</h1>
              <p>Aqui podras encontar las mejores recetas de las cafeterias.</p>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carruselexamplecaptions" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carruselexamplecaptions" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1>Acerca de nosotros</h1>
          <p class="lead text-muted">
              Este sitio fue creado a duras penas, nos costó reunirnos espero tenga compacion profe vivi y gracias por mover la entrega para el viernes 6 aunque nos costó igual

          </p>
          
        </div>
      </section>
    
      <div class="album py-5 bg-light">
        <div class="container">
    
          <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <img src="{% static 'img/cafe1.jfif' %}" alt="" width="348" height="250">
                
                <div class="card-body">
                  <h5>Sobre el cafe</h5>
                  <p class="card-text">El cafe que todos tomamos día a día, antes de cada clase normalmente se nos hace muy monotono, a lo cual nosotros recurrimos a variar la forma de disfrutar esta bebida que mayor parte de los alumnos y profesores comparte en las mañana.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <img src="{% static 'img/compu1.jfif' %}" alt="" width="348" height="250">
                <div class="card-body">
                  <h5 >¿Quienes somos?</h5>
                  <p class="card-text">Somos un grupo de estudiantes a los cuales les interesa la preparacion de los distintos tipos de cafe, los cuales queremos compartir con la gente que ingrese a este blog con sus respectivas criticas y reseñas que haran que este sitio mejore cada vez más.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
               <img src="{% static 'img/duoc1.jfif' %}" alt="" width="348" height="250">                      
               <div class="card-body">
                 <h5>Nuestra institucion</h5>
                  <p class="card-text">DuocUC fue fundado por iniciativa de un grupo de estudiantes de la Pontificia Universidad Católica de Chile en el contexto de la reforma universitaria, bajo el nombre de Departamento Universitario Obrero y Campesino,​ por el primer rector laico de la Universidad Católica.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
         
            {% endblock %}

trabajo_fase_2/web/templates/saladas.html
{% extends "base_generic.html" %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}">

    <title>Toffe</title>
    <link rel="icon" href="img/icon.jpg">
  </head>

  <body>
    {% block content %}
    <header>

    </header>
    <section  class="jumbotron bg-info">
      <div class="container ">
        <h1 class="h1"> <strong>Novedades de las Recetas</strong> </h1>
        <p class="h2"><strong>Desde los pasteles hasta las bebidas.</strong> </p>
      </div>
    </section>
    </header>
      
    
    <section class="main container">
        <nav aria-label="breadcrumb">
            <section class="col-md-9">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
                <li class="breadcrumb-item"><a href="{% url 'novedades' %}">Categoría</a></li>
                <li class="breadcrumb-item active">Recetas saladas</li>
                
              </ol>
          <article class="post clearfix">
            <a href="{% url 'pret' %}" class="thumb pull-left">
              <img src="{% static 'img/pret1.jpg' %}" alt="" style="float: left;" width="400" height="250"><h2 class="h2-2"><strong>Receta de pretzel, paso a paso</strong></h2>
            </a>
            <p><span class="psfecha">12 de Octubre del 2020</span> por <span class="posts autor"><a href="#">Bastian Pinto</a></span></p>
            <p class="pcontenido text-justify">
                Un pretzel es un tipo de galleta o bollo horneado, y retorcido en forma de lazo, con un sabor ligeramente salado. Su origen se encuentra en Alemania, y es bastante popular en Alsacia, la Suiza alemana, Austria y América del Norte.
            </p>

            <div class="botones">
              <a href="{% url 'pret' %}" class="btn btn-info">Leer Más</a>
            </div>
          </article>
        </section>
    </section>

    
    
   
   

  </body>
  
 
      
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock %}

trabajo_fase_2/web/templates/web/autor_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Eliminar autor</h1>

<p>¿Estas seguro de eliminar al autor: {{ autor }}? </p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" action="" value="Si, eliminar" />
</form>

{% endblock %}

trabajo_fase_2/web/templates/web/autor_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Autor: {{ autor }} </h1>
<p>{{autor.fechanac}}-{% if autor.fechamuerte %}{{autor.fechamuerte}}{% endif %} </p>

<div style="margin-left:20px;margin-top:20px;">
<h4>Recetas</h4>

<dl>    
{% for receta in autor.receta_set.all %}
    <dt><a href="{% url 'receta-detail' receta.pk %}"></a></dt>
    <dd>{{receta.receta}}</dd>
    {% endfor %}
</dl>
</div>



{% endblock %}

trabajo_fase_2/web/templates/web/autor_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type ="submit" value="Añadir" />
</form>
{% endblock %}